package org.domain.avaluosapl.entity;

// Generated 14/03/2015 10:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Activo generated by hbm2java
 */
@Entity
@Table(name = "activo", catalog = "db_acinversiones")
public class Activo implements java.io.Serializable {

	private Integer idActivo;
	private String nombre;
	private String descripcion;
	private byte estado;
	private int idCliente;
	private Set<Avaluo> avaluos = new HashSet<Avaluo>(0);
	private Tangible tangible;

	public Activo() {
	}

	public Activo(String nombre, String descripcion, byte estado, int idCliente) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.idCliente = idCliente;
	}

	public Activo(String nombre, String descripcion, byte estado,
			int idCliente, Set<Avaluo> avaluos, Tangible tangible) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.idCliente = idCliente;
		this.avaluos = avaluos;
		this.tangible = tangible;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_activo", unique = true, nullable = false)
	public Integer getIdActivo() {
		return this.idActivo;
	}

	public void setIdActivo(Integer idActivo) {
		this.idActivo = idActivo;
	}

	@Column(name = "nombre", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", nullable = false)
	public byte getEstado() {
		return this.estado;
	}

	public void setEstado(byte estado) {
		this.estado = estado;
	}

	@Column(name = "id_cliente", nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activo")
	public Set<Avaluo> getAvaluos() {
		return this.avaluos;
	}

	public void setAvaluos(Set<Avaluo> avaluos) {
		this.avaluos = avaluos;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "activo")
	public Tangible getTangible() {
		return this.tangible;
	}

	public void setTangible(Tangible tangible) {
		this.tangible = tangible;
	}

}
