package org.domain.avaluosapl.entity;

// Generated 14/03/2015 10:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AEconomica generated by hbm2java
 */
@Entity
@Table(name = "a_economica", catalog = "db_acinversiones")
public class AEconomica implements java.io.Serializable {

	private int idAEconomica;
	private String descripcion;
	private Set<PersonaJuridica> personaJuridicas = new HashSet<PersonaJuridica>(
			0);

	public AEconomica() {
	}

	public AEconomica(int idAEconomica, String descripcion) {
		this.idAEconomica = idAEconomica;
		this.descripcion = descripcion;
	}

	public AEconomica(int idAEconomica, String descripcion,
			Set<PersonaJuridica> personaJuridicas) {
		this.idAEconomica = idAEconomica;
		this.descripcion = descripcion;
		this.personaJuridicas = personaJuridicas;
	}

	@Id
	@Column(name = "id_a_economica", unique = true, nullable = false)
	public int getIdAEconomica() {
		return this.idAEconomica;
	}

	public void setIdAEconomica(int idAEconomica) {
		this.idAEconomica = idAEconomica;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "AEconomica")
	public Set<PersonaJuridica> getPersonaJuridicas() {
		return this.personaJuridicas;
	}

	public void setPersonaJuridicas(Set<PersonaJuridica> personaJuridicas) {
		this.personaJuridicas = personaJuridicas;
	}

}
