package org.domain.avaluosapl.entity;

// Generated 14/03/2015 10:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CasoUso generated by hbm2java
 */
@Entity
@Table(name = "caso_uso", catalog = "db_acinversiones")
public class CasoUso implements java.io.Serializable {

	private Integer idCasoUso;
	private String codigo;
	private String descripcion;
	private Set<Permiso> permisos = new HashSet<Permiso>(0);

	public CasoUso() {
	}

	public CasoUso(String codigo) {
		this.codigo = codigo;
	}

	public CasoUso(String codigo, String descripcion, Set<Permiso> permisos) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.permisos = permisos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_caso_uso", unique = true, nullable = false)
	public Integer getIdCasoUso() {
		return this.idCasoUso;
	}

	public void setIdCasoUso(Integer idCasoUso) {
		this.idCasoUso = idCasoUso;
	}

	@Column(name = "codigo", nullable = false, length = 25)
	@NotNull
	@Length(max = 25)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 1500)
	@Length(max = 1500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoUso")
	public Set<Permiso> getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

}
