package org.domain.avaluosapl.entity;

// Generated 24/03/2015 11:16:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "db_acinversiones")
public class Cliente implements java.io.Serializable {

	private int idClientePersona;
	private Persona persona;
	private Date fechaIngreso;
	private Set<PersonaJuridica> personaJuridicas = new HashSet<PersonaJuridica>(
			0);

	public Cliente() {
	}

	public Cliente(Persona persona, Date fechaIngreso) {
		this.persona = persona;
		this.fechaIngreso = fechaIngreso;
	}

	public Cliente(Persona persona, Date fechaIngreso,
			Set<PersonaJuridica> personaJuridicas) {
		this.persona = persona;
		this.fechaIngreso = fechaIngreso;
		this.personaJuridicas = personaJuridicas;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "persona"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_cliente_persona", unique = true, nullable = false)
	public int getIdClientePersona() {
		return this.idClientePersona;
	}

	public void setIdClientePersona(int idClientePersona) {
		this.idClientePersona = idClientePersona;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 0)
	@NotNull
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<PersonaJuridica> getPersonaJuridicas() {
		return this.personaJuridicas;
	}

	public void setPersonaJuridicas(Set<PersonaJuridica> personaJuridicas) {
		this.personaJuridicas = personaJuridicas;
	}

}
