package org.domain.avaluosapl.entity;

// Generated 14/03/2015 10:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Concepto generated by hbm2java
 */
@Entity
@Table(name = "concepto", catalog = "db_acinversiones")
public class Concepto implements java.io.Serializable {

	private Integer idConcepto;
	private String nombre;
	private Set<ItemAvaluo> itemAvaluos = new HashSet<ItemAvaluo>(0);

	public Concepto() {
	}

	public Concepto(String nombre) {
		this.nombre = nombre;
	}

	public Concepto(String nombre, Set<ItemAvaluo> itemAvaluos) {
		this.nombre = nombre;
		this.itemAvaluos = itemAvaluos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_concepto", unique = true, nullable = false)
	public Integer getIdConcepto() {
		return this.idConcepto;
	}

	public void setIdConcepto(Integer idConcepto) {
		this.idConcepto = idConcepto;
	}

	@Column(name = "nombre", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concepto")
	public Set<ItemAvaluo> getItemAvaluos() {
		return this.itemAvaluos;
	}

	public void setItemAvaluos(Set<ItemAvaluo> itemAvaluos) {
		this.itemAvaluos = itemAvaluos;
	}

}
