package org.domain.avaluosapl.entity;

// Generated 24/03/2015 11:16:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name = "forma_pago", catalog = "db_acinversiones")
public class FormaPago implements java.io.Serializable {

	private Integer idFormaPago;
	private String descripcion;
	private Set<Factura> facturas = new HashSet<Factura>(0);

	public FormaPago() {
	}

	public FormaPago(String descripcion) {
		this.descripcion = descripcion;
	}

	public FormaPago(String descripcion, Set<Factura> facturas) {
		this.descripcion = descripcion;
		this.facturas = facturas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_forma_pago", unique = true, nullable = false)
	public Integer getIdFormaPago() {
		return this.idFormaPago;
	}

	public void setIdFormaPago(Integer idFormaPago) {
		this.idFormaPago = idFormaPago;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPago")
	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

}
