package org.domain.avaluosapl.entity;

// Generated 14/03/2015 10:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ItemAvaluo generated by hbm2java
 */
@Entity
@Table(name = "item_avaluo", catalog = "db_acinversiones")
public class ItemAvaluo implements java.io.Serializable {

	private Integer idItemAvaluo;
	private Concepto concepto;
	private Avaluo avaluo;
	private double costo;
	private double utilidad;
	private ItemFactura itemFactura;
	private Set<ManoObra> manoObras = new HashSet<ManoObra>(0);

	public ItemAvaluo() {
	}

	public ItemAvaluo(Concepto concepto, Avaluo avaluo, double costo,
			double utilidad) {
		this.concepto = concepto;
		this.avaluo = avaluo;
		this.costo = costo;
		this.utilidad = utilidad;
	}

	public ItemAvaluo(Concepto concepto, Avaluo avaluo, double costo,
			double utilidad, ItemFactura itemFactura, Set<ManoObra> manoObras) {
		this.concepto = concepto;
		this.avaluo = avaluo;
		this.costo = costo;
		this.utilidad = utilidad;
		this.itemFactura = itemFactura;
		this.manoObras = manoObras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_item_avaluo", unique = true, nullable = false)
	public Integer getIdItemAvaluo() {
		return this.idItemAvaluo;
	}

	public void setIdItemAvaluo(Integer idItemAvaluo) {
		this.idItemAvaluo = idItemAvaluo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concepto_ia", nullable = false)
	@NotNull
	public Concepto getConcepto() {
		return this.concepto;
	}

	public void setConcepto(Concepto concepto) {
		this.concepto = concepto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_avaluo_ia", nullable = false)
	@NotNull
	public Avaluo getAvaluo() {
		return this.avaluo;
	}

	public void setAvaluo(Avaluo avaluo) {
		this.avaluo = avaluo;
	}

	@Column(name = "costo", nullable = false, precision = 22, scale = 0)
	public double getCosto() {
		return this.costo;
	}

	public void setCosto(double costo) {
		this.costo = costo;
	}

	@Column(name = "utilidad", nullable = false, precision = 22, scale = 0)
	public double getUtilidad() {
		return this.utilidad;
	}

	public void setUtilidad(double utilidad) {
		this.utilidad = utilidad;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "itemAvaluo")
	public ItemFactura getItemFactura() {
		return this.itemFactura;
	}

	public void setItemFactura(ItemFactura itemFactura) {
		this.itemFactura = itemFactura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemAvaluo")
	public Set<ManoObra> getManoObras() {
		return this.manoObras;
	}

	public void setManoObras(Set<ManoObra> manoObras) {
		this.manoObras = manoObras;
	}

}
