package org.domain.avaluosapl.entity;

// Generated 1/04/2015 07:29:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * ItemFactura generated by hbm2java
 */
@Entity
@Table(name = "item_factura", catalog = "db_acinversiones")
public class ItemFactura implements java.io.Serializable {

	private Integer idItemAvaluoFac;
	private ItemAvaluo itemAvaluo;
	private Factura factura;
	private int cantidad;
	private double valorUnitario;

	public ItemFactura() {
	}

	public ItemFactura(ItemAvaluo itemAvaluo, Factura factura, int cantidad,
			double valorUnitario) {
		this.itemAvaluo = itemAvaluo;
		this.factura = factura;
		this.cantidad = cantidad;
		this.valorUnitario = valorUnitario;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "itemAvaluo"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_item_avaluo_fac", unique = true, nullable = false)
	public Integer getIdItemAvaluoFac() {
		return this.idItemAvaluoFac;
	}

	public void setIdItemAvaluoFac(Integer idItemAvaluoFac) {
		this.idItemAvaluoFac = idItemAvaluoFac;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public ItemAvaluo getItemAvaluo() {
		return this.itemAvaluo;
	}

	public void setItemAvaluo(ItemAvaluo itemAvaluo) {
		this.itemAvaluo = itemAvaluo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_factura_if", nullable = false)
	@NotNull
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "valor_unitario", nullable = false, precision = 22, scale = 0)
	public double getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(double valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

}
