package org.domain.avaluosapl.entity;

// Generated 14/03/2015 10:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoDoc generated by hbm2java
 */
@Entity
@Table(name = "tipo_doc", catalog = "db_acinversiones", uniqueConstraints = @UniqueConstraint(columnNames = "abbr"))
public class TipoDoc implements java.io.Serializable {

	private Integer idTipoDoc;
	private String abbr;
	private String descripcion;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public TipoDoc() {
	}

	public TipoDoc(String descripcion) {
		this.descripcion = descripcion;
	}

	public TipoDoc(String abbr, String descripcion, Set<Persona> personas) {
		this.abbr = abbr;
		this.descripcion = descripcion;
		this.personas = personas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tipo_doc", unique = true, nullable = false)
	public Integer getIdTipoDoc() {
		return this.idTipoDoc;
	}

	public void setIdTipoDoc(Integer idTipoDoc) {
		this.idTipoDoc = idTipoDoc;
	}

	@Column(name = "abbr", unique = true, length = 5)
	@Length(max = 5)
	public String getAbbr() {
		return this.abbr;
	}

	public void setAbbr(String abbr) {
		this.abbr = abbr;
	}

	@Column(name = "descripcion", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDoc")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
