package org.domain.prueba.entity;

// Generated 24/03/2015 11:16:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Calificacion generated by hbm2java
 */
@Entity
@Table(name = "calificacion", catalog = "db_acinversiones")
public class Calificacion implements java.io.Serializable {

	private Integer idCalificacion;
	private String descripcion;
	private Set<Colaborador> colaboradors = new HashSet<Colaborador>(0);

	public Calificacion() {
	}

	public Calificacion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Calificacion(String descripcion, Set<Colaborador> colaboradors) {
		this.descripcion = descripcion;
		this.colaboradors = colaboradors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_calificacion", unique = true, nullable = false)
	public Integer getIdCalificacion() {
		return this.idCalificacion;
	}

	public void setIdCalificacion(Integer idCalificacion) {
		this.idCalificacion = idCalificacion;
	}

	@Column(name = "descripcion", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calificacion")
	public Set<Colaborador> getColaboradors() {
		return this.colaboradors;
	}

	public void setColaboradors(Set<Colaborador> colaboradors) {
		this.colaboradors = colaboradors;
	}

}
