package org.domain.prueba.entity;

// Generated 24/03/2015 11:16:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", catalog = "db_acinversiones")
public class Direccion implements java.io.Serializable {

	private Integer idDireccion;
	private Persona persona;
	private String direccion;

	public Direccion() {
	}

	public Direccion(Persona persona, String direccion) {
		this.persona = persona;
		this.direccion = direccion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_direccion", unique = true, nullable = false)
	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_dir", nullable = false)
	@NotNull
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "direccion", nullable = false, length = 1500)
	@NotNull
	@Length(max = 1500)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
