package org.domain.prueba.entity;

// Generated 24/03/2015 11:16:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * Tangible generated by hbm2java
 */
@Entity
@Table(name = "tangible", catalog = "db_acinversiones")
public class Tangible implements java.io.Serializable {

	private int idActivoTan;
	private Activo activo;
	private Double valorNum;
	private Date fechaAdq;

	public Tangible() {
	}

	public Tangible(Activo activo) {
		this.activo = activo;
	}

	public Tangible(Activo activo, Double valorNum, Date fechaAdq) {
		this.activo = activo;
		this.valorNum = valorNum;
		this.fechaAdq = fechaAdq;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "activo"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_activo_tan", unique = true, nullable = false)
	public int getIdActivoTan() {
		return this.idActivoTan;
	}

	public void setIdActivoTan(int idActivoTan) {
		this.idActivoTan = idActivoTan;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Activo getActivo() {
		return this.activo;
	}

	public void setActivo(Activo activo) {
		this.activo = activo;
	}

	@Column(name = "valor_num", precision = 22, scale = 0)
	public Double getValorNum() {
		return this.valorNum;
	}

	public void setValorNum(Double valorNum) {
		this.valorNum = valorNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_adq", length = 0)
	public Date getFechaAdq() {
		return this.fechaAdq;
	}

	public void setFechaAdq(Date fechaAdq) {
		this.fechaAdq = fechaAdq;
	}

}
