package org.domain.prueba.entity;

// Generated 24/03/2015 11:16:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name = "tipo_contrato", catalog = "db_acinversiones")
public class TipoContrato implements java.io.Serializable {

	private Integer idTipoContrato;
	private String descripcion;
	private Set<Colaborador> colaboradors = new HashSet<Colaborador>(0);

	public TipoContrato() {
	}

	public TipoContrato(String descripcion) {
		this.descripcion = descripcion;
	}

	public TipoContrato(String descripcion, Set<Colaborador> colaboradors) {
		this.descripcion = descripcion;
		this.colaboradors = colaboradors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tipo_contrato", unique = true, nullable = false)
	public Integer getIdTipoContrato() {
		return this.idTipoContrato;
	}

	public void setIdTipoContrato(Integer idTipoContrato) {
		this.idTipoContrato = idTipoContrato;
	}

	@Column(name = "descripcion", nullable = false, length = 125)
	@NotNull
	@Length(max = 125)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
	public Set<Colaborador> getColaboradors() {
		return this.colaboradors;
	}

	public void setColaboradors(Set<Colaborador> colaboradors) {
		this.colaboradors = colaboradors;
	}

}
